name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    name: "${{ matrix.job_name }} (Ruby ${{ matrix.ruby_version }})"
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        include:
          - job_name: "Style Check"
            step_name: Run RuboCop
            script_file: fmt
            ruby_version: "2.5"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: "Set Up Ruby ${{ matrix.ruby_version }}"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true
      - name: ${{ matrix.step_name }}
        run:  bash script/${{ matrix.script_file }}
